export const MESSAGE_CODES = {

  SUCCESS: {
    PATIENT_CREATED: 'PATIENT_CREATED',
    PATIENT_UPDATED: 'PATIENT_UPDATED',
    PATIENT_DELETED: 'PATIENT_DELETED',
    PROFESSIONAL_CREATED: 'PROFESSIONAL_CREATED',
    PROFESSIONAL_UPDATED: 'PROFESSIONAL_UPDATED',
    PROFESSIONAL_DELETED: 'PROFESSIONAL_DELETED',
    APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
    APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
    APPOINTMENT_DELETED: 'APPOINTMENT_DELETED',
    PATIENTS_RETRIEVED: 'PATIENTS_RETRIEVED',
    PROFESSIONALS_RETRIEVED: 'PROFESSIONALS_RETRIEVED',
    APPOINTMENTS_RETRIEVED: 'APPOINTMENTS_RETRIEVED',
    OPERATION_SUCCESS: 'OPERATION_SUCCESS',
    NOTES_UPDATED: 'NOTES_UPDATED'
  },
  
  ERROR: {
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
    PROFESSIONAL_NOT_FOUND: 'PROFESSIONAL_NOT_FOUND',
    APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    APPOINTMENT_CONFLICT: 'APPOINTMENT_CONFLICT', 
    NETWORK_ERROR: 'NETWORK_ERROR'
  }
};

export const VALIDATION_CODES = {
  FORM_FIELDS_REQUIRED: 'FORM_FIELDS_REQUIRED',
  NAME_MUST_BE_STRING: 'NAME_MUST_BE_STRING',
  NAME_MIN_LENGTH: 'NAME_MIN_LENGTH',
  NAME_INVALID_CHARACTERS: 'NAME_INVALID_CHARACTERS',
  EMAIL_INVALID_FORMAT: 'EMAIL_INVALID_FORMAT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    PHONE_INVALID_FORMAT: 'PHONE_INVALID_FORMAT',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  BIRTHDATE_INVALID: 'BIRTHDATE_INVALID'
};

export default { MESSAGE_CODES, VALIDATION_CODES };