export const MESSAGE_CODES = {
  SUCCESS: {
    PATIENT_CREATED: "PATIENT_CREATED",
    PATIENT_UPDATED: "PATIENT_UPDATED",
    PATIENT_DELETED: "PATIENT_DELETED",
    PROFESSIONAL_CREATED: "PROFESSIONAL_CREATED",
    PROFESSIONAL_UPDATED: "PROFESSIONAL_UPDATED",
    PROFESSIONAL_DELETED: "PROFESSIONAL_DELETED",
    APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
    APPOINTMENT_UPDATED: "APPOINTMENT_UPDATED",
    APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
    APPOINTMENT_DELETED: "APPOINTMENT_DELETED",
    PATIENTS_RETRIEVED: "PATIENTS_RETRIEVED",
    PROFESSIONALS_RETRIEVED: "PROFESSIONALS_RETRIEVED",
    APPOINTMENTS_RETRIEVED: "APPOINTMENTS_RETRIEVED",
    OPERATION_SUCCESS: "OPERATION_SUCCESS",
    NOTES_UPDATED: "NOTES_UPDATED",
    LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
    PASSWORD_CHANGED: "PASSWORD_CHANGED",
    LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL"
  },

  ERROR: {
    VALIDATION_FAILED: "VALIDATION_FAILED",
    PATIENT_NOT_FOUND: "PATIENT_NOT_FOUND",
    PROFESSIONAL_NOT_FOUND: "PROFESSIONAL_NOT_FOUND",
    APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    APPOINTMENT_CONFLICT: "APPOINTMENT_CONFLICT",
    NETWORK_ERROR: "NETWORK_ERROR",
    PATIENT_CREATINFO_FAILED: "PATIENT_CREATING_FAILED",
    TOKEN_NOT_PROVIDED: "TOKEN_NOT_PROVIDED",
    INVALID_TOKEN: "INVALID_TOKEN", 
    INVALID_USER: "INVALID_USER",
    INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
    UNAUTHORIZED_PROFILE_ACCESS: "UNAUTHORIZED_PROFILE_ACCESS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INCORRECT_PASSWORD: "INCORRECT_PASSWORD"
  }
};

export const VALIDATION_CODES = {
  FORM_FIELDS_REQUIRED: "FORM_FIELDS_REQUIRED",
  NAME_MUST_BE_STRING: "NAME_MUST_BE_STRING",
  NAME_MIN_LENGTH: "NAME_MIN_LENGTH",
  NAME_INVALID_CHARACTERS: "NAME_INVALID_CHARACTERS",
  END_TIME_BEFORE_START_TIME: "END_TIME_BEFORE_START_TIME",
  APPOINTMENT_IN_PAST: "APPOINTMENT_IN_PAST",
  APPOINTMENT_CONFLICT: "APPOINTMENT_CONFLICT",
  EMAIL_INVALID_FORMAT: "EMAIL_INVALID_FORMAT",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PHONE_INVALID_FORMAT: "PHONE_INVALID_FORMAT",
  PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",
  DNI_INVALID_FORMAT: "DNI_INVALID_FORMAT",
  BIRTHDATE_INVALID: "BIRTHDATE_INVALID",
  NOTES_HTML_NOT_ALLOWED: "NOTES_HTML_NOT_ALLOWED",
  NOTES_TOO_LONG: "NOTES_TOO_LONG",
  ID_INVALID_FORMAT: "ID_INVALID_FORMAT",
  DNI_ALREADY_EXISTS: "DNI_ALREADY_EXISTS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  UNAUTHORIZED_ACTION: "UNAUTHORIZED_ACTION"
};

export default { MESSAGE_CODES, VALIDATION_CODES };
